layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: https://jabc.ca/summer-accelerator/
  # youtube: your_username

topics:
  - name: HighTechU
    web_url: https://hightechuca
    image_url: https://pbs.twimg.com/profile_images/1407446480181358596/ZJT9pAFv_400x400.jpg

  - name: Junior Achievement of BC
    web_url: https://jabc.ca/
    image_url: https://heartpress.ca/wp-content/uploads/2017/05/Junior-Achievement-BC.jpg

  - name: Alacrity Canada
    web_url: https://alacritycanada.com/
    image_url: https://media-exp1.licdn.com/dms/image/C560BAQHqdI7RqTnbIA/company-logo_200_200/0/1519892773826?e=1642636800&v=beta&t=Or7AUPSk7kyL76zcDRMG7WHysqEiZnUDZrjMEjDuI50
    
  - name: Capital Investment Network
    web_url: https://www.capinvestment.net/
    image_url: https://media-exp1.licdn.com/dms/image/C560BAQEqyNAeh5_P-Q/company-logo_200_200/0/1563899761281?e=1642636800&v=beta&t=Lt64GmPkd0vMaytAfSzusMbBRs_a_vi-nd3qnJzlQJY