layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  exclude:
    archived: false
    forks: false
    projects:
    - personal-website
    - accelerator-portfolio
    - pathways2quantum
    - portfolio
    - hightechu-academy-papyruscity
    - hightechu-summer2020
    - hello
    - hightechu-academy-stickyboard 
    - skills-lab-covid19
    - hightechu-academy-victorianaloxonemap
    - hightechu-academy-meetmaps
    - hightechu-openspace
    - hightechu-ez-distancing
    - hightechq
    - official-website
    - internship-application-CSJ-2020
    - hightechu-academy-questionanswer
    - hightechu-academy-autogenda
    - hightechu-academy-eventpro
    - hightechu-academy-emojiland
    - hightechu-academy-hashtagproject
    - hightechu-academy-homeworkhelper
    - hightechu-academy-zooloo
    - hightechu-academy-zenplanner
    - hightechu-academy-gigs
    - hightechu-academy-productivitycalculator
    - hightechu-academy-giftme
    - hightechu-academy-homerecipie
    - hightechu-academy-forestfiredetector
    - hightechu-academy-bubblet
    - hightechu-academy-radbag
    - hightechu-academy-effortlessdistancing
    - hightechu-spring2019
    - hightechu wp-bootrap-navwalker
    - hightechu-academy-project-fantasticblackberry 
    - flarum-ext-aqueduct 
    - sci-fi-or-fantasy-data 
    - hub-project-scifi-or-fantasy 
    - hub-project-say-what-you-see 
    - hightechu-academy-homerecipe 
    - jasonette 
    - links
    - hightechu-discord-bot 
    - wp-bootstrap-navwalker 

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: https://jabc.ca/summer-accelerator/
  # youtube: your_username

topics:

  - name: Junior Achievement of BC
    web_url: https://jabc.ca/
    image_url: https://heartpress.ca/wp-content/uploads/2017/05/Junior-Achievement-BC.jpg

  - name: Alacrity Canada
    web_url: https://alacritycanada.com/
    image_url: https://media-exp1.licdn.com/dms/image/C560BAQHqdI7RqTnbIA/company-logo_200_200/0/1519892773826?e=1642636800&v=beta&t=Or7AUPSk7kyL76zcDRMG7WHysqEiZnUDZrjMEjDuI50
    
  - name: Capital Investment Network
    web_url: https://www.capinvestment.net/
    image_url: https://media-exp1.licdn.com/dms/image/C560BAQEqyNAeh5_P-Q/company-logo_200_200/0/1563899761281?e=1642636800&v=beta&t=Lt64GmPkd0vMaytAfSzusMbBRs_a_vi-nd3qnJzlQJY
